---
# GitLab Admin Password Reset Playbook
# Usage: ansible-playbook -i inventory.ini gitlab-password-reset.yml
# 
# Options:
#   --extra-vars "new_password=YourNewPassword123!"
#   --extra-vars "username=root"
#   --extra-vars "create_new_admin=true admin_username=newadmin admin_email=admin@company.com"

- name: GitLab Admin Password Reset
  hosts: gitlab_servers
  become: yes
  vars:
    # Default values - can be overridden with --extra-vars
    username: "root"
    new_password: "SecR3t!P4ssw0rd#2025"  # More complex password
    create_new_admin: false
    admin_username: "admin"
    admin_email: "admin@example.com"

  tasks:
    # ===== PRE-CHECKS =====
    - name: Verify GitLab services are running
      shell: gitlab-ctl status
      register: gitlab_status
      failed_when: false
      changed_when: false

    - name: Display GitLab service status
      debug:
        msg: "{{ gitlab_status.stdout_lines }}"

    - name: Fail if GitLab services are not running
      fail:
        msg: "GitLab services are not running. Please start GitLab first with 'sudo gitlab-ctl start'"
      when: "'run:' not in gitlab_status.stdout"

    # ===== PASSWORD RESET FOR EXISTING USER =====
    - name: Reset password for existing user
      shell: |
        gitlab-rails console -e production << 'RAILS_EOF'
        begin
          # Find user by username
          user = User.find_by(username: '{{ username }}')
          
          if user.nil?
            puts "❌ User '{{ username }}' not found!"
            exit 1
          end
          
          puts "Found user: #{user.username} (ID: #{user.id}, Email: #{user.email})"
          
          # Set new password
          user.password = '{{ new_password }}'
          user.password_confirmation = '{{ new_password }}'
          
          # Ensure user is not blocked
          user.state = 'active' if user.blocked?
          
          # Save changes
          if user.save!
            puts "✅ Password successfully changed for user: #{user.username}"
            puts "New password: {{ new_password }}"
          else
            puts "❌ Error saving password:"
            puts user.errors.full_messages.join(', ')
            exit 1
          end
        rescue => e
          puts "❌ Error occurred: #{e.message}"
          exit 1
        end
        RAILS_EOF
      register: password_reset_result
      when: not create_new_admin

    - name: Display password reset result
      debug:
        var: password_reset_result.stdout_lines
      when: not create_new_admin

    # ===== CREATE NEW ADMIN USER =====
    - name: Create new admin user
      shell: |
        gitlab-rails console -e production << 'RAILS_EOF'
        begin
          # Check if user already exists
          existing_user = User.find_by(username: '{{ admin_username }}')
          if existing_user
            puts "User '{{ admin_username }}' already exists. Resetting password instead..."
            user = existing_user
          else
            # Create new admin user
            user = User.new(
              username: '{{ admin_username }}',
              email: '{{ admin_email }}',
              name: '{{ admin_username.title }}',
              admin: true,
              confirmed_at: Time.now,
              state: 'active'
            )
          end
          
          # Set password
          user.password = '{{ new_password }}'
          user.password_confirmation = '{{ new_password }}'
          user.admin = true
          
          if user.save!
            action = existing_user ? "updated" : "created"
            puts "✅ Admin user successfully #{action}!"
            puts "Username: #{user.username}"
            puts "Email: #{user.email}"
            puts "Password: {{ new_password }}"
            puts "Admin: #{user.admin?}"
          else
            puts "❌ Error #{existing_user ? 'updating' : 'creating'} admin user:"
            puts user.errors.full_messages.join(', ')
            exit 1
          end
        rescue => e
          puts "❌ Error occurred: #{e.message}"
          exit 1
        end
        RAILS_EOF
      register: admin_create_result
      when: create_new_admin

    - name: Display admin user creation result
      debug:
        var: admin_create_result.stdout_lines
      when: create_new_admin

    # ===== VERIFICATION =====
    - name: Verify user exists and get info
      shell: |
        gitlab-rails console -e production << 'RAILS_EOF'
        username = '{{ admin_username if create_new_admin else username }}'
        user = User.find_by(username: username)
        
        if user
          puts "✅ User verification successful:"
          puts "  Username: #{user.username}"
          puts "  Email: #{user.email}"
          puts "  ID: #{user.id}"
          puts "  Admin: #{user.admin?}"
          puts "  State: #{user.state}"
          puts "  Confirmed: #{user.confirmed?}"
        else
          puts "❌ User '#{username}' not found after operation"
          exit 1
        end
        RAILS_EOF
      register: user_verification
      changed_when: false

    - name: Display user verification
      debug:
        var: user_verification.stdout_lines

    # ===== FINAL INSTRUCTIONS =====
    - name: Display login instructions
      debug:
        msg:
          - "🎉 GitLab password reset completed successfully!"
          - ""
          - "Login Information:"
          - "  URL: http://{{ ansible_default_ipv4.address }}"
          - "  Username: {{ admin_username if create_new_admin else username }}"
          - "  Password: {{ new_password }}"
          - ""
          - "⚠️  Please change this password after logging in for security!"
          - ""
          - "Additional Commands:"
          - "  Check GitLab status: sudo gitlab-ctl status"
          - "  View GitLab logs: sudo gitlab-ctl tail"

    - name: Get GitLab system info
      shell: |
        echo "=== GitLab System Information ==="
        gitlab-rake gitlab:env:info 2>/dev/null | head -10 || echo "Could not get GitLab info"
        echo ""
        echo "=== User Count ==="
        gitlab-rails runner "puts 'Total users: ' + User.count.to_s" 2>/dev/null || echo "Could not get user count"
        echo ""
        echo "=== Admin Users ==="
        gitlab-rails runner "User.admins.each { |u| puts '- ' + u.username + ' (' + u.email + ')' }" 2>/dev/null || echo "Could not get admin users"
      register: gitlab_info
      changed_when: false
      tags: [info]

    - name: Display GitLab system info
      debug:
        var: gitlab_info.stdout_lines
      tags: [info]

  # ===== USAGE EXAMPLES IN PLAYBOOK =====
  # 
  # Basic usage (reset root password):
  # ansible-playbook -i inventory.ini gitlab-password-reset.yml
  #
  # Reset specific user password:
  # ansible-playbook -i inventory.ini gitlab-password-reset.yml --extra-vars "username=someuser new_password=NewPass123!"
  #
  # Create new admin user:
  # ansible-playbook -i inventory.ini gitlab-password-reset.yml --extra-vars "create_new_admin=true admin_username=myadmin admin_email=me@company.com new_password=AdminPass123!"
  #
  # Get system info only:
  # ansible-playbook -i inventory.ini gitlab-password-reset.yml --tags info