import subprocess
import random
from typing import Optional
from rich.console import Console

console = Console()


def add_all() -> None:
    subprocess.run(["git", "add", "."], check=True)


def commit(message: str = "[ci]: generated by larek cli") -> bool:
    try:
        subprocess.run(
            ["git", "commit", "-m", message],
            capture_output=True,
            text=True,
            check=True,
        )
        return True
    except subprocess.CalledProcessError:
        return False


def ensure_remote(name: str, url: str) -> str:
    """Add remote if missing, otherwise set-url. Returns 'added' or 'updated'."""
    try:
        subprocess.run(
            ["git", "remote", "add", name, url], check=True, capture_output=True
        )
        return "added"
    except subprocess.CalledProcessError:
        subprocess.run(["git", "remote", "set-url", name, url], check=True)
        return "updated"


def current_branch() -> Optional[str]:
    try:
        res = subprocess.run(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        )
        return res.stdout.strip()
    except Exception:
        return None


def checkout(branch: str) -> None:
    """Checkout an existing branch."""
    subprocess.run(["git", "checkout", branch], check=True)


def create_and_checkout_branch(branch: str) -> Optional[str]:
    """Create branch if missing and checkout it. Returns previous branch name."""
    prev = current_branch()
    # Check if branch exists locally
    res = subprocess.run(
        ["git", "rev-parse", "--verify", branch],
        capture_output=True,
        text=True,
        check=False,
    )
    if res.returncode == 0:
        try:
            subprocess.run(["git", "checkout", branch], check=True, capture_output=True)
        except subprocess.CalledProcessError:
            suffix = "".join(
                random.choices("abcdefghijklmnopqrstuvwxyz0123456789", k=4)
            )
            new_branch = f"{branch}-{suffix}"
            subprocess.run(["git", "checkout", "-b", new_branch], check=True)
            console.print(
                f"[yellow]Could not checkout '{branch}' due to local changes — using '{new_branch}' instead.[/yellow]"
            )
    else:
        # Create new branch and check it out
        subprocess.run(["git", "checkout", "-b", branch], check=True)
    return prev


def fetch(remote: str = "origin") -> None:
    subprocess.run(["git", "fetch", remote], check=True)


def pull_rebase(remote: str = "origin", branch: Optional[str] = None) -> None:
    branch = branch or current_branch() or "main"
    subprocess.run(["git", "pull", "--rebase", remote, branch], check=True)


def push_all(remote: str = "origin") -> bool:
    try:
        subprocess.run(["git", "push", "-u", remote, "--all"], check=True)
        return True
    except subprocess.CalledProcessError:
        return False


def push_force_with_lease(remote: str = "origin") -> None:
    subprocess.run(
        ["git", "push", "-u", remote, "--all", "--force-with-lease"], check=True
    )
